- name: Install nodejs repo
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

- name: Install nodejs service
  ansible.builtin.yum:
    name:
      - nodejs
    state: latest

- name: add application user and download app files
  import_tasks: app-user-setup.yml

- name: Install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: update {{COMPONENT}} systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes