
- name: Install python service
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: application user setup and download app files
  import_tasks: app-user-setup.yml

- name: Install specified python requirements
  pip:
    requirements: /home/roboshop/{{COMPONENTS}}/requirements.txt
    executable: pip3.3



#
#- name: update {{COMPONENT}} systemd file
#  ansible.builtin.template:
#    src: systemd.service
#    dest: /etc/systemd/system/{{COMPONENT}}.service
#
#- name: start {{COMPONENT}} service
#  ansible.builtin.systemd:
#    name: "{{COMPONENT}}"
#    state: restarted
#    enabled: yes
#    daemon_reload: yes